### ISSUE TITLE
User story - Logo

### ISSUE THREAD

**Issue by RachWalm** [KTC96/Didyouhearthat#36]
### Story

As a **developer**, I can **have a logo** so that I can **achieve brand consistency**.

### Acceptance Criteria

- An excellent logo that fits the theme and design of rest of site that we all like

### Tasks

- [ ] Discuss design colours and theme with CSS organiser
- [ ] Design a logo
- [ ] Share with the team

**Comment by RachWalm** [comment]
Natalia has found a suitable logo so if Alex hasn't started I am happy to go with hers and close this out.

**Comment by RachWalm** [comment]
Alex will try some colours out on the logo that Natalia found.

**Comment by alex025x** [comment]
Tried some new colors but they dont fit, the logo Natalia chose looks good.
